language: java
jdk: oraclejdk8
jobs:
  include:
    - stage: build
      script: mvn -B -V -DskipTests clean install
    - stage: test
      env:
        - TYPE=glassfish-module
      script: ./.travis/tests.sh ${TYPE}
    - stage: test
      env:
        - TYPE=glassfish-bundled
      script: ./.travis/tests.sh ${TYPE}
